name: heuristic
on: workflow_dispatch
jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion command-not-found coreutils cron debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1:amd64 libmecab2:amd64 libpam-runtime libpcre2-8-0:amd64 libpython3.13-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace mailcap man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-zope.interface python3.13 rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget
          pip install setuptools==80.9.0
      - run: |
          python -m pip install --upgrade pip
      - run: |
          python -m pip install --upgrade tox
      - run: |
          tox -e ci-py$(echo "3.13" | tr -d '.') -- -v --color=yes
    env:
      COLUMNS: '254'
      GIT_CONFIG_PARAMETERS: "'log.showSignature'='false'"
      LC_CTYPE: C.UTF-8
      LINES: '62'
      PYTHONHASHSEED: '3320168117'
      PYTHONIOENCODING: utf-8
      PYTHONNOUSERSITE: '1'
      PYTHONWARNDEFAULTENCODING: '1'
      TERM: xterm
  uvloop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion command-not-found cron debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1:amd64 libmecab2:amd64 libpam-runtime libpcre2-8-0:amd64 libpython3.13-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace mailcap man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-zope.interface python3.13 rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget
          pip install setuptools==80.9.0 wheel==0.45.1
      - run: |
          python -m pip install pip --upgrade --disable-pip-version-check
      - run: |
          python -m pip install -e ".[uvloop]"
      - run: |
          python -m black --check src/ tests/
    env:
      GIT_CONFIG_PARAMETERS: "'log.showSignature'='false'"
      PYTHONNOUSERSITE: '1'
