name: hybrid

on: workflow_dispatch

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
      - run: |
          python -m pip install --upgrade tox
      - run: |
          tox -e ci-py$(echo "${{ matrix.python-version }}" | tr -d '.') -- -v --color=yes
    env:
      GIT_CONFIG_PARAMETERS: "'log.showSignature'='false'"

  uvloop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install pip --upgrade --disable-pip-version-check
      - run: |
          python -m pip install -e ".[uvloop]"
      - run: |
          python -m black --check src/ tests/
    env:
      GIT_CONFIG_PARAMETERS: "'log.showSignature'='false'"
